import { Arsenal } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";

const arsenal = Arsenal({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={arsenal.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
